create table netology.CUSTOMERS
(
    id int generated by default as identify primary key,
    name varchar not null,
    surname varchar not null,
    age int not null,
    phone_number varchar not null
);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('Vadim', 'Volkov', 33, 89528880088);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('Danila', 'Volkov', 3, 89527770077);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('Olga', 'Volkova', 32, 89151180404);

