create table netology.ORDERS
(
    id int generated by default as identity primary key,
    date timestamp not null,
    customer_id int,
    product_name varchar not null,
    amount int not null,
    foreign key (customer_id) references netology.CUSTOMERS(id)
);

insert into netology.ORDERS ("date", customer_id, product_name, amount)
values (current_date, 7, lexus, 1);